# Generated by Django 5.0.7 on 2024-08-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customusermodel_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
